version: v3

teleport:
  nodename: acer-mgmt-teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO

auth_service:
  enabled: true
  cluster_name: acer-mgmt
  listen_addr: 0.0.0.0:3025
  authentication:
    type: local
    second_factor: otp
    webauthn:
      rp_id: teleport.imcherry5778.xyz
  session_recording_config:
    mode: proxy-sync
  proxy_listener_mode: separate

proxy_service:
  enabled: true
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport.imcherry5778.xyz:3080
  listen_addr: 0.0.0.0:3023
  ssh_public_addr: teleport.imcherry5778.xyz:3023
  tunnel_listen_addr: 0.0.0.0:3024
  tunnel_public_addr: teleport.imcherry5778.xyz:3024
  kube_listen_addr: 0.0.0.0:3026
  kube_public_addr: teleport.imcherry5778.xyz:3026
  https_keypairs:
    - cert_file: /run/teleport/tls/tls.crt
      key_file: /run/teleport/tls/tls.key
  https_keypairs_reload_interval: 1h

ssh_service:
  enabled: false

kubernetes_service:
  enabled: false

db_service:
  enabled: false

discovery_service:
  enabled: false

app_service:
  enabled: true
  apps:
    - name: grafana
      uri: http://grafana:3000
      public_addr: tp-grafana.imcherry5778.xyz
      rewrite:
        redirect: [grafana.imcherry5778.xyz]
      labels:
        env: mgmt
        owner: observability
    - name: kibana
      uri: http://kibana:5601
      public_addr: tp-kibana.imcherry5778.xyz
      rewrite:
        redirect: [kibana.imcherry5778.xyz]
      labels:
        env: mgmt
        owner: observability
    - name: prometheus
      uri: http://prometheus:9090
      public_addr: tp-prometheus.imcherry5778.xyz
      rewrite:
        redirect: [prometheus.imcherry5778.xyz]
      labels:
        env: mgmt
        owner: observability
    - name: alertmanager
      uri: http://alertmanager:9093
      public_addr: tp-alertmanager.imcherry5778.xyz
      rewrite:
        redirect: [alertmanager.imcherry5778.xyz]
      labels:
        env: mgmt
        owner: observability
    - name: keycloak
      uri: http://keycloak:8080
      public_addr: tp-keycloak.imcherry5778.xyz
      rewrite:
        redirect: [keycloak.imcherry5778.xyz]
        headers:
          - "Host: tp-keycloak.imcherry5778.xyz"
          - "Origin: https://tp-keycloak.imcherry5778.xyz:3080"
      labels:
        env: mgmt
        owner: security
    - name: vault
      uri: https://vault:8200
      public_addr: tp-vault.imcherry5778.xyz
      rewrite:
        redirect: [vault.imcherry5778.xyz]
      insecure_skip_verify: true
      labels:
        env: mgmt
        owner: security
    - name: netbox
      uri: http://netbox:8080
      public_addr: tp-netbox.imcherry5778.xyz
      rewrite:
        redirect: [netbox.imcherry5778.xyz]
      labels:
        env: mgmt
        owner: infra
