{
 "title": "oje Workload Pod Allocation",
 "tags": [
  "opencost",
  "workload-allocation",
  "oje_cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_allocation{cluster=\"oje\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top Pods By Estimated Hourly Allocation Cost",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(20, sum by (namespace,pod,node) ((container_cpu_allocation{cluster=\"oje\",namespace=~\"$namespace\"} * on(cluster,node) group_left() node_cpu_hourly_cost{cluster=\"oje\"}) + ((container_memory_allocation_bytes{cluster=\"oje\",namespace=~\"$namespace\"} / 1024 / 1024 / 1024) * on(cluster,node) group_left() node_ram_hourly_cost{cluster=\"oje\"})))",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Top Pods By CPU Allocation",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "topk(20, sum by (namespace,pod,node) (container_cpu_allocation{cluster=\"oje\", namespace=~\"$namespace\"}))",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Top Pods By Memory Allocation",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, sum by (namespace,pod,node) (container_memory_allocation_bytes{cluster=\"oje\", namespace=~\"$namespace\"}))",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Workload Allocation Cost Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod) ((container_cpu_allocation{cluster=\"oje\",namespace=~\"$namespace\"} * on(cluster,node) group_left() node_cpu_hourly_cost{cluster=\"oje\"}) + ((container_memory_allocation_bytes{cluster=\"oje\",namespace=~\"$namespace\"} / 1024 / 1024 / 1024) * on(cluster,node) group_left() node_ram_hourly_cost{cluster=\"oje\"}))",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}