{
 "title": "worker2 Nodes",
 "tags": [
  "Monitoring",
  "kubernetes-nodes",
  "khb_cluster",
  "worker2"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg (rate(node_cpu_seconds_total{job=\"kubernetes-nodes\", user=\"khb\", instance=\"worker2\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"kubernetes-nodes\", user=\"khb\", instance=\"worker2\"} / node_memory_MemTotal_bytes{job=\"kubernetes-nodes\", user=\"khb\", instance=\"worker2\"})) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Disk Usage /",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{job=\"kubernetes-nodes\", user=\"khb\", instance=\"worker2\", mountpoint=\"/\", fstype!~\"tmpfs|overlay|squashfs|ramfs\"} / node_filesystem_size_bytes{job=\"kubernetes-nodes\", user=\"khb\", instance=\"worker2\", mountpoint=\"/\", fstype!~\"tmpfs|overlay|squashfs|ramfs\"}))",
     "legendFormat": "Disk Usage /"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum (rate(node_network_receive_bytes_total{job=\"kubernetes-nodes\", user=\"khb\", instance=\"worker2\", device!~\"lo|veth.*|docker.*|br-.*|cni.*|flannel.*|tailscale.*\"}[5m])) * 8 / 1024 / 1024",
     "legendFormat": "Network RX"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum (rate(node_network_transmit_bytes_total{job=\"kubernetes-nodes\", user=\"khb\", instance=\"worker2\", device!~\"lo|veth.*|docker.*|br-.*|cni.*|flannel.*|tailscale.*\"}[5m])) * 8 / 1024 / 1024",
     "legendFormat": "Network TX"
    }
   ]
  }
 ]
}