input {
  kafka {
    id => "logs_from_kafka_buffer"
    bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS:kafka:19092}"
    topics => ["${LOGS_KAFKA_TOPIC:logs.buffered}"]
    group_id => "logstash-elasticsearch"
    client_id => "logstash-consumer"
    codec => json
    auto_offset_reset => "earliest"
  }
}
