output {
  if [labels][log_type] == "system" {
    if [@metadata][pipeline] {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "logs-system-%{[labels][team]}-%{+YYYY.MM.dd}"
        pipeline => "%{[@metadata][pipeline]}"
      }
    }
    else {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "logs-system-%{[labels][team]}-%{+YYYY.MM.dd}"
      }
    }
  }
  else if [labels][log_type] == "docker" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "logs-docker-%{[labels][team]}-%{+YYYY.MM.dd}"
    }
  }
  else if [labels][log_type] == "k3d" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "logs-k3d-%{[labels][team]}-%{+YYYY.MM.dd}"
    }
  }
  else if [labels][log_type] in ["infra", "openstack"] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "logs-openstack-%{[labels][team]}-%{+YYYY.MM.dd}"
    }
  }
  else if [labels][log_type] in ["k8s", "kubernetes"] {
    if [@metadata][pipeline] {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "logs-kubernetes-%{[labels][team]}-%{+YYYY.MM.dd}"
        pipeline => "%{[@metadata][pipeline]}"
      }
    }
    else {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "logs-kubernetes-%{[labels][team]}-%{+YYYY.MM.dd}"
      }
    }
  }
  else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "logs-service-%{[labels][team]}-%{+YYYY.MM.dd}"
    }
  }
}
