output {
  # [분류 규칙 5] log_type이 'infra'인 로그(호스트 OS, OpenStack)는 infra 전용 인덱스로 전송합니다.
  if [log_type] == "infra" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "infra-logs-%{user}-%{+YYYY.MM.dd}"
    }
  }
  # 그 외 K8s 컨테이너 및 애플리케이션 로그는 k8s 전용 인덱스로 전송합니다.
  else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "k8s-logs-%{user}-%{+YYYY.MM.dd}"
    }
  }
}
