{
 "title": "Active Cluster OpenCost workload allocation",
 "tags": [
  "opencost",
  "active-cluster",
  "template"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Active cluster",
    "query": {
     "query": "label_values(node_total_hourly_cost, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_allocation{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_allocation{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Workload Snapshot", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "x": 0, "y": 1, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (namespace,pod) (container_cpu_allocation{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}))"
    }
   ]
  },
  {
   "title": "Selected Pod $/hr",
   "type": "stat",
   "gridPos": { "x": 6, "y": 1, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((container_cpu_allocation{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"} * on(cluster,node) group_left() node_cpu_hourly_cost{cluster=~\"$cluster\"}) + ((container_memory_allocation_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"} / 1024 / 1024 / 1024) * on(cluster,node) group_left() node_ram_hourly_cost{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "CPU Allocated",
   "type": "stat",
   "gridPos": { "x": 12, "y": 1, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_cpu_allocation{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "stat",
   "gridPos": { "x": 18, "y": 1, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_allocation_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  { "title": "Most Expensive Workloads", "type": "row", "gridPos": { "x": 0, "y": 5, "w": 24, "h": 1 } },
  {
   "title": "Top Pods By Hourly Cost",
   "type": "table",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(20, sum by (namespace,pod,node) ((container_cpu_allocation{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"} * on(cluster,node) group_left() node_cpu_hourly_cost{cluster=~\"$cluster\"}) + ((container_memory_allocation_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"} / 1024 / 1024 / 1024) * on(cluster,node) group_left() node_ram_hourly_cost{cluster=~\"$cluster\"})))",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Top Pod Cost Now",
   "type": "bargauge",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(12, sum by (namespace,pod,node) ((container_cpu_allocation{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"} * on(cluster,node) group_left() node_cpu_hourly_cost{cluster=~\"$cluster\"}) + ((container_memory_allocation_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"} / 1024 / 1024 / 1024) * on(cluster,node) group_left() node_ram_hourly_cost{cluster=~\"$cluster\"})))",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  { "title": "Resource Drivers", "type": "row", "gridPos": { "x": 0, "y": 15, "w": 24, "h": 1 } },
  {
   "title": "Top Pods By CPU Allocation",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(15, sum by (namespace,pod,node) (container_cpu_allocation{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}))",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Top Pods By Memory Allocation",
   "type": "bargauge",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(15, sum by (namespace,pod,node) (container_memory_allocation_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}))",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Top Pod Cost Trend",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(12, sum by (namespace,pod,node) ((container_cpu_allocation{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"} * on(cluster,node) group_left() node_cpu_hourly_cost{cluster=~\"$cluster\"}) + ((container_memory_allocation_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"} / 1024 / 1024 / 1024) * on(cluster,node) group_left() node_ram_hourly_cost{cluster=~\"$cluster\"})))",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}