{
 "title": "nmg Namespace Cost",
 "tags": [
  "opencost",
  "namespace-cost",
  "nmg_cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_allocation{cluster=\"nmg\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace Estimated Hourly Allocation Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (namespace) ((container_cpu_allocation{cluster=\"nmg\",namespace=~\"$namespace\"} * on(cluster,node) group_left() node_cpu_hourly_cost{cluster=\"nmg\"}) + ((container_memory_allocation_bytes{cluster=\"nmg\",namespace=~\"$namespace\"} / 1024 / 1024 / 1024) * on(cluster,node) group_left() node_ram_hourly_cost{cluster=\"nmg\"}))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace CPU Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (namespace) (container_cpu_allocation{cluster=\"nmg\", namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace Memory Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (container_memory_allocation_bytes{cluster=\"nmg\", namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Current Namespace Cost Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) ((container_cpu_allocation{cluster=\"nmg\",namespace=~\"$namespace\"} * on(cluster,node) group_left() node_cpu_hourly_cost{cluster=\"nmg\"}) + ((container_memory_allocation_bytes{cluster=\"nmg\",namespace=~\"$namespace\"} / 1024 / 1024 / 1024) * on(cluster,node) group_left() node_ram_hourly_cost{cluster=\"nmg\"})))",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}